# openapi2-functions.yaml
swagger: '2.0'
info:
  title: resumeapi descriptionexample
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /getvisitors:
    get:
      summary: Return count of total page hits
      operationId: visitorcounter
      x-google-backend:
        address: https://us-east1-resume-challenge-kyle-3.cloudfunctions.net/resume-visitor-counter-function
        jwt_audience: https://us-east1-resume-challenge-kyle-3.cloudfunctions.net/resume-visitor-counter-function

      responses:
        '200':
          description: A successful response
          schema:
            type: string
