# openapi2-functions.yaml
swagger: '2.0'
info:
  title: resumeapi descriptionexample
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /getvisitors:
    get:
      summary: Greet a user
      operationId: visitorcounter
      x-google-backend:
        address: https://us-east1-strange-cycle-371319.cloudfunctions.net/function-2
        jwt_audience: https://us-east1-strange-cycle-371319.cloudfunctions.net/function-2

      responses:
        '200':
          description: A successful response
          schema:
            type: string
