name: Update Google Function Website Files
run-name: ${{ github.actor }} is updating the api gateway config
on: 
  push: 
    paths: 
      'Back End Files/APIGateway/**'

env:
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
  GCS_PROJECT: ${{ secrets.GCS_PROJECT }}

jobs:
  example-job-name:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    # actions/checkout MUST come before auth
    - name: Checkout
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/585423355911/locations/global/workloadIdentityPools/githubpool/providers/providerid'
        service_account: 'sa-githubpublish@strange-cycle-371319.iam.gserviceaccount.com'
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply



  end-to-end-test:
    needs: example-job-name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5 # use the explicit version number
        with:
          install: npm run install
