name: Update Google Function Website Files
run-name: ${{ github.actor }} is updating the api gateway config
on: 
  push: 
    paths: 
      'Back End Files/APIGateway/**'

env:
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
  GCS_PROJECT: ${{ secrets.GCS_PROJECT }}

jobs:
  example-job-name:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    # actions/checkout MUST come before auth
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/585423355911/locations/global/workloadIdentityPools/githubpool/providers/providerid'
        service_account: 'sa-githubpublish@strange-cycle-371319.iam.gserviceaccount.com'
    
    - name: 'set unique date variable'
      run: echo "MY_DATE=$(date +%Y%m%d%H%M)" >> $GITHUB_EN
    
    - name: 'create new api config with unique name'
      run: 'gcloud api-gateway api-configs create kyleapiconfig${{ env.MY_DATE }} --api=resumeapi --openapi-spec=Back\ End\ Files/APIGateway/openapi2-functions.yaml --project=$GCS_PROJECT --backend-auth-service-account=sa-githubpublish@strange-cycle-371319.iam.gserviceaccount.com'
      
    - name: 'view details about api config'
      run: 'gcloud api-gateway api-configs describe kyleapiconfig --api=resumeapi --project=$GCS_PROJECT'

    - name: 'deploy api gateway'
      run: 'gcloud api-gateway gateways update apigateway10 --api-config=kyleapiconfig${{ env.MY_DATE }} --api=resumeapi --location=us-east1 --project=$GCS_PROJECT '
      
    - name: 'See details about the gateway'
      run: 'gcloud api-gateway gateways describe apigateway10 --location=us-east1 --project=$GCS_PROJECT'
