name: Terraform Reset

on: issue_comment

permissions: read-all


jobs:
  terraform-reset:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo "Event:" 
          echo ${{ toJSON(github.event) }}