name: Update Front End Website Files
run-name: ${{ github.actor }} is pushing resumeproject website files (like html and css files) to the gcp bucket
on:
  push:
    paths:
      - 'Front\ End\ Files/**'
      - '.github/workflows/**'
      
env:
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
  
jobs:
  deploy-website-update:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # actions/checkout MUST come before auth
      - name: Checkout
        uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/585423355911/locations/global/workloadIdentityPools/githubpool/providers/providerid'
          service_account: 'sa-githubpublish@strange-cycle-371319.iam.gserviceaccount.com'

      - name: Find creds file
        run: ls
      - name: find creds file 2
        run: ls ../


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform -chdir=terraform/ init

      - name: Terraform Validate
        run: terraform -chdir=terraform/ validate

      - name: Terraform Plan
        run: terraform -chdir=terraform/ plan
        continue-on-error: true

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform -chdir=terraform/ apply

  end-to-end-test:
    needs: deploy-website-update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5 # use the explicit version number
        with:
          install: npm run install
