name: Update Front End Website Files
run-name: ${{ github.actor }} is pushing resumeproject website files (like html and css files) to the gcp bucket
on:
  push:
    paths:
      - 'Front\ End\ Files/**'
      
env:
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
  
jobs:
  deploy-website-update:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    # actions/checkout MUST come before auth
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/585423355911/locations/global/workloadIdentityPools/githubpool/providers/providerid'
        service_account: 'sa-githubpublish@strange-cycle-371319.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Update the website files'
      run: 'gsutil -m rsync -r -c -d Front\ End\ Files gs://$GCS_BUCKET'

  end-to-end-test:
    needs: deploy-website-update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5 # use the explicit version number
        with:
          install: npm run install
          start: npm run cy:run
