name: Update cloud infrastructure
run-name: ${{ github.actor }} is updating cloud files and infrastructure
on:
  push:
    paths:
      - 'Front\ End\ Files/**'
      - 'Back\ End\ Files/**'
      - '.github/workflows/**'
      - 'terraform/**'
      
env:
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
  TF_VAR_GOOGLE_GHA_CREDS_PATH: $GOOGLE_GHA_CREDS_PATH
  
jobs:
  build:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # actions/checkout MUST come before auth
      - name: Checkout
        uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/585423355911/locations/global/workloadIdentityPools/githubpool/providers/providerid'
          service_account: 'sa-githubpublish@strange-cycle-371319.iam.gserviceaccount.com'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        env:
          TF_VAR_GOOGLE_GHA_CREDS_PATH: ${{ env.GOOGLE_GHA_CREDS_PATH }}

      - name: Terraform Init
        run: terraform -chdir=terraform/resume-architecture/ init
        env:
          TF_VAR_GOOGLE_GHA_CREDS_PATH: ${{ env.GOOGLE_GHA_CREDS_PATH }}

      - name: Terraform Validate
        run: terraform -chdir=terraform/resume-architecture/ validate
        env:
          TF_VAR_GOOGLE_GHA_CREDS_PATH: ${{ env.GOOGLE_GHA_CREDS_PATH }}

      - name: Terraform Plan
        run: terraform -chdir=terraform/resume-architecture/ plan -out=planfile
        continue-on-error: true
        env:
          TF_VAR_GOOGLE_GHA_CREDS_PATH: ${{ env.GOOGLE_GHA_CREDS_PATH }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform -chdir=terraform/resume-architecture/ apply "planfile"
        env:
          TF_VAR_GOOGLE_GHA_CREDS_PATH: ${{ env.GOOGLE_GHA_CREDS_PATH }}


  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        id: cypress_test
        uses: cypress-io/github-action@v5 # use the explicit version number
        with:
          #install: npm run install
          script: npx cypress run > testresults

  publish-artifact:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/585423355911/locations/global/workloadIdentityPools/githubpool/providers/providerid'
          service_account: 'sa-githubpublish@strange-cycle-371319.iam.gserviceaccount.com'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        env:
          TF_VAR_GOOGLE_GHA_CREDS_PATH: ${{ env.GOOGLE_GHA_CREDS_PATH }}

      - name: Terraform Init
        run: terraform -chdir=terraform/publish-artifacts/ init
        env:
          TF_VAR_GOOGLE_GHA_CREDS_PATH: ${{ env.GOOGLE_GHA_CREDS_PATH }}

      - name: Terraform Validate
        run: terraform -chdir=terraform/publish-artifacts/ validate
        env:
          TF_VAR_GOOGLE_GHA_CREDS_PATH: ${{ env.GOOGLE_GHA_CREDS_PATH }}

      - name: Terraform Plan
        run: terraform -chdir=terraform/publish-artifacts/ plan -out=planfile
        continue-on-error: true
        env:
          TF_VAR_GOOGLE_GHA_CREDS_PATH: ${{ env.GOOGLE_GHA_CREDS_PATH }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform -chdir=terraform/publish-artifacts/ apply "planfile"
        env:
          TF_VAR_GOOGLE_GHA_CREDS_PATH: ${{ env.GOOGLE_GHA_CREDS_PATH }}
