name: Update cloud infrastructure
run-name: Infrastructure Pipeline
on:
  push:
    paths:
      - 'Back\ End\ Files/**'
      - '.github/workflows/**'
      - 'terraform/**'
      - 'cypress/**'
      - '**.tf'

jobs:

  deploySiteInfrastructure:
    #needs: build
    runs-on: ubuntu-latest
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: write      

    steps:
      
      - name: Check Out Repository
        uses: 'actions/checkout@v4'

      #auth so we can use gcloud. make sure to have run the oidc infr before this and updated these attributes
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          create_credentials_file: 'true'
          workload_identity_provider: 'projects/356251802763/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: github-actions-sa@resume-challenge-kyle-3.iam.gserviceaccount.com

      # #auth and setup to terraform cloud
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
     
      #run the terraform that sets up the infrastructure 
      - name: Apply Infrastructure Terraform 
        run: cd infra; terraform init; terraform plan 

      #run some end to end tests using cypress
      - name: End to End Functional Tests (Cypress)
        uses: cypress-io/github-action@v5 # use the explicit version number
        


  staticVulnScan:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: write
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results

    steps:
      - name: Checkout
        uses: 'actions/checkout@v3'

      #vuln scan the infrastructure deployment terraform
      - name: Run Checkov Action
        uses: bridgecrewio/checkov-action@v12
        with:
          soft_fail: true # optional: do not return an error code if there are failed checks
          output_format: cli, sarif # optional: the output format, one of: cli, json, junitxml, github_failed_only, or sarif. Default: sarif
          output_file_path: console,results.sarif # folder and name of results file
          download_external_modules: true # optional: download external terraform modules from public git repositories and terraform registry

      - name: Upload SARIF File
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

  # #     #vuln scan the build terraform
  # #     - name: Run Checkov action
  # #       uses: bridgecrewio/checkov-action@master
  # #       with:
  # #         directory: terraform/publish-artifacts/
  # #         soft_fail: true # optional: do not return an error code if there are failed checks
  # #         framework: terraform # optional: run only on a specific infrastructure {cloudformation,terraform,kubernetes,all}
  # #         output_format: cli # optional: the output format, one of: cli, json, junitxml, github_failed_only, or sarif. Default: sarif
  # #         output_file_path: vuln-scan-reports/vulnscan-build-results.sarif # folder and name of results file
  # #         download_external_modules: true # optional: download external terraform modules from public git repositories and terraform registry
  # #         log_level: DEBUG # optional: set log level. Default WARNING
  # #         #config_file: path/this_file

  # #     #publish the checkov scan to a bucket using gcloud
  # #     # - name: upload checkov results to bucket
  # #     #   run: gcloud storage cp -r vuln-scan-reports/ gs://resume-function-code-bucket/
