name: Update cloud infrastructure
run-name: Infrastructure Pipeline
on:
  push:
    paths:
      - 'Back\ End\ Files/**'
      - '.github/workflows/**'
      - 'terraform/**'
      - 'cypress/**'
      - '**.tf'

jobs:

  deploySiteInfrastructure:
    #needs: build
    runs-on: ubuntu-latest
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      
      - name: Check Out Repository
        uses: 'actions/checkout@v4'

      #auth so we can use gcloud. make sure to have run the oidc infr before this and updated these attributes
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          create_credentials_file: 'true'
          workload_identity_provider: 'projects/356251802763/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: github-actions-sa@resume-challenge-kyle-3.iam.gserviceaccount.com

      # #auth and setup to terraform cloud
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
     
      #run the terraform that sets up the infrastructure 
      - name: Apply Infrastructure Terraform 
        run: cd infra; terraform init; terraform plan 

      #run some end to end tests using cypress
      - name: End to End Functional Tests (Cypress)
        uses: cypress-io/github-action@v5 # use the explicit version number
        
  staticVulnScan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      contents: write

    steps:
      - name: Checkout
        uses: 'actions/checkout@v3'

      #vuln scan the infrastructure deployment terraform
      - name: Checkov Terraform Scan
        if: always()  
        uses: bridgecrewio/checkov-action@v12
        with:
          output_format: cli, sarif # optional: the output format, one of: cli, json, junitxml, github_failed_only, or sarif. Default: sarif
          output_file_path: console,vulnresults/checkov-results.sarif # folder and name of results file
          download_external_modules: true # optional: download external terraform modules from public git repositories and terraform registry
          hard_fail_on: 'HIGH,CRITICAL'

      #vuln scan the python 3.6 code
      - name: Snyk Python 3.6 Vulnerability Scan
        if: always()  
        uses: snyk/actions/python-3.6@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=vulnresults/python-results.sarif --severity-threshold=medium

      #vuln scan the Node code
      - name: Snyk Node Vulnerability Scan
        if: always()
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=vulnresults/node-results.sarif --severity-threshold=medium

      #vuln scan the iac code
      - name: Snyk IaC Vulnerability Scan
        if: always()
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=vulnresults/iacsnyk-results.sarif --severity-threshold=medium

      #sbom creation
      - name: SBOM  
        if: always()
        uses: anchore/sbom-action@v0
        with:
          path: '.'
          format: spdx-json
          output-file: "${{ github.event.repository.name }}-sbom.spdx.json"
          dependency-snapshot: 'true'
      
      #gryft SBOM scan
      - name: Scan SBOM
        id: SBOM-scan
        if: always()
        uses: anchore/scan-action@v3
        with:
          sbom: "${{ github.event.repository.name }}-sbom.spdx.json"
          fail-build: true
          severity-cutoff: high
          output-format: sarif

      - name: Save SBOM Scan Results
        run: cat ${{ steps.SBOM-scan.outputs.sarif }} > vulnresults/SBOM-results.sarif
        

      #upload the sarif file results to github actions security
      - name: Upload SARIF Files to Github Security
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: vulnresults


